// Autogenerated by Thrift Compiler (facebook)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// @generated

package graph

import (
	"bytes"
	"context"
	"fmt"
	nebula0 "github.com/JimWen/nebula-go/v3/nebula"
	thrift "github.com/facebook/fbthrift/thrift/lib/go/thrift"
	"sync"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = sync.Mutex{}
var _ = bytes.Equal
var _ = context.Background

var _ = nebula0.GoUnusedProtection__

func init() {
}
